[quote.epigraph, , Ps. 66:16]
____
Venid, oíd todos los que teméis a Dios,
y contaré lo que Él ha hecho a mi alma.
____

== La Vida de Alice Hayes

Ha estado en mi corazón por muchos años,
dejar un breve relato de los tratos del Señor conmigo desde mi juventud hasta este día,
para animar a los jóvenes a la fidelidad y a la confianza continua en el Señor,
que nunca defrauda a los que dependen verdaderamente en Él,
tanto en las misericordias temporales como en las espirituales.

Nací en Rickmansworth, en Hertfordshire, en el año 1657, de padres honestos,
que me educaron en la religión de la adoración pública de la iglesia de Inglaterra.
Mi madre, murió cuando yo era muy joven; pero mientras vivió,
fue una madre tierna y afectuosa conmigo, casi en exceso.
Un ejemplo de su cariño hacia mí fue muy notable.
En una ocasión, al encontrarme muy débil y creyendo que estaba cerca de la muerte,
produjo en mi madre una angustia tan fuerte,
que se postró sobre sus rodillas y le oró al Señor que tomara su vida y perdonara la mía;
lo cual Él hizo, por razones que solamente Él conoce.

Continué viviendo en la casa de mi padre hasta alrededor de los dieciséis años,
bajo la rigurosa tutela de una madrastra,
cuyo trato severo hacia mí hizo que me cansara de vivir con ella,
tanto así que dejé la casa de mi padre, y me fui a trabajar como criada,^
footnote:[Durante este tiempo, las mujeres jóvenes y solteras,
se comprometían a menudo bajo un contrato por varios años
como sirvientas o institutrices en familias grandes,
con el fin de asistir a la cabeza de familia con varios deberes
domésticos y también en la crianza y educación de sus hijos.]
para poder vivir más en paz que antes.
El Señor en misericordia se acordó de mí y miró mi aflicción en aquel día,
aunque todavía no había llegado al conocimiento de la verdad.
En aquellos días,
me persiguió en mi consciencia con Sus reprensiones por los pecados de mi juventud,
que eran, bailar, cantar, contar historias vanas, entre otros pasatiempos,
en los que los jóvenes son muy propensos a caer.
Y al no ser reprendida por mis padres por estas cosas, ni por el sacerdote,
continué contristando al Espíritu Santo en mí,
sin saber aún qué era lo que me reprobaba en secreto por estas cosas; aunque,
gracias a la gran misericordia y bondad del Señor hacia mí,
no fui esclava de males peores por el resto de mis días.

Sin embargo,
cuando Aquel que escudriña todos los corazones vino con Su luz para abrir mi entendimiento,
y exponer mis pecados delante de mis ojos,
y para darme a conocer qué era lo que me reprendía por el tiempo que había malgastado,
entonces (¡oh, entonces!) el tiempo de angustia para Jacob^
footnote:[Jeremías 30:7]
fue experimentado.
Oh, me resultaba terrible considerar cómo había pasado por alto las reprensiones del Todopoderoso,
y a menudo estaba lista para lamentarme de esta manera:--"`¡Oh,
si hubiera tenido padres que me hubieran informado de que
esas cosas (por las que fui reprendida) eran realmente malas;
o que me hubieran dicho que esas reprensiones que sentía a menudo,
eran de parte del Espíritu del Señor! ¡Sin duda, nunca hubiera hecho lo que hice!`"
Pero ni mis padres, ni el sacerdote, me enseñaron tal doctrina;
ambos consideraban todas esas cosas como pasatiempos inocentes e inofensivos.
Y en cuanto a la luz, gracia, o Espíritu de Dios que me reprendía,
nunca había escuchado que hubiera algo tan cerca
de mí como lo sentí y lo encontré. Entonces,
me dolió pensar que el Señor de la gloria estuviera llamando
por tanto tiempo a la puerta de mi oscuro corazón,
esperando entrar en él, y que lo había dejado afuera por tanto tiempo,
aunque Él aún así me seguía con Sus juicios,
y en gran misericordia para con mi pobre alma a menudo
me llevaba a una profunda tristeza.

La seria consideración sobre mi final fue puesta seriamente delante de mí,
junto con pensamientos acerca de la eternidad,
y las palabras "`eternamente y para siempre`" se apoderaron de mí. Entonces, ¡oh,
la aflicción y confusión en que me encontraba!
Hasta el punto de no poder decidir qué camino tomar,
ni a quién dar a conocer mi angustiada condición.
A veces me iba a buscar la compañía de otras personas,
intentando así calmar mi pena; pero no funcionaba.
Entonces buscaba algún lugar secreto,
y allí caía sobre mis rodillas y derramaba mi espíritu ante el Señor,
implorando misericordia y perdón.

Ahora, relataré cómo la sabia mano del Todopoderoso me guio.
Después que dejé la casa de mi padre, fui en busca de un lugar para trabajar,
y pronto escuché de uno en el que permanecí por un tiempo,
y fui muy querida en esa familia.
Les serví con honestidad y en amor.
Pero tal vez no esté de más decir cómo dediqué mi tiempo (con respecto
a la religión) en el primer lugar de servicio donde trabajé,
y fue de esta manera: Asistía diligente y constantemente al culto público,
siempre que se me presentaba la oportunidad.
A menudo iba sola a lugares retirados para orar,
y me deleitaba grandemente leyendo las Escrituras, y memorizando versículos.
Y mientras trabajaba, mi corazón meditaba en las cosas buenas,
y estaba muy contenta de encontrarme lejos de la
casa de mi padre debido a la quietud que disfrutaba.
En aquellos días, a menudo mi corazón fue consolado, aunque no sabía de dónde provenía.

Mientras continuaba haciendo el bien, según lo mejor de mí conocimiento,
el Señor se complació en aparecerse de una forma extraordinaria,
y tuve una dulce visitación. Fui llevada a un silencio profundo delante del Señor,
donde fui enseñada a esperar, y no me atrevía a pronunciar mis propias palabras.
Y aunque había reunido en mi cerebro muchas palabras buenas y frases de las Escrituras,
llegué a ver que ahora esto no era suficiente.
Invertí mi tiempo de esta manera y fue un buen momento
para mí. Esto fue obra del Señor y a Él sea la alabanza;
¡alabado sea Su nombre por siempre!

Después de un tiempo, fui a vivir a la casa de un juez de paz,
donde mi primer esposo y yo nos conocimos.
Pero, primero debo mencionar,
que fui a la casa de mi hermano por un período corto
antes de empezar a trabajar en mi segundo empleo,
y mientras me encontraba ahí,
escuché un rumor en el vecindario de una mujer que
predicaba que era muy estimada entre los Cuáqueros,
y que iba a estar en una de sus reuniones no muy lejos de la casa de mi hermano.
Algunos de los vecinos, solo por curiosidad, querían oírla y verla,
y entonces me pidieron que los acompañara; a lo que accedí. Cuando llegué a la reunión,
me impactó profundamente.
La seriedad de las personas, y el profundo estado de reverencia en el que se encontraban,
ocasionó que muchos profundos pensamientos atravesaran mi corazón,
al contemplar tanta diferencia entre su forma de
adorar y la de aquellos donde yo solía asistir.
Después de un tiempo en silencio, una mujer se levantó y habló,
y su testimonio afectó de tal forma mi corazón y
enterneció mi espíritu que no podía parar de llorar.
Pero, ¡ay!, al finalizar la reunión,
el enemigo en seguida prevaleció de nuevo y oscureció
el poco sentido espiritual que tenía,
utilizando tanto medios externos como sugerencias internas,
de modo que no volví a asistir a una reunión de este tipo durante varios años.

Cuando llegó el momento de comenzar mi trabajo sirviendo en la casa del juez, mi ama,
poco tiempo después de haber estado con ella, a menudo decía:
"`Esta Alice se convertirá en una Cuáquera;`" aunque entonces,
yo no tenía tales intenciones.
Sin embargo, debido a la bondad del Señor hacia mí,
invertía todo mi tiempo libre ya sea leyendo o estando a solas,
o en alguna actividad religiosa,
siendo además diligente y fiel con el cargo que mis
amos me encomendaron (para su consuelo y el mío),
sintiéndome muy agradecida del lugar en donde me encontraba.

Fue en esta familia, como mencioné anteriormente, que conocí a mi primer esposo,
Daniel Smith, quien en amor me pidió la mano,
y continuamos juntos en esa familia cerca de dos años. Al final de ese tiempo,
le plació al Señor visitarme con una dolorosa cojera
ocasionada por un esguince en el tobillo;
pero continué trabajando por algún tiempo más.

En ese invierno,
mis amos se mudaron a Londres y no tuvieron la necesidad de contratar
a tantos empleados en la ciudad como solían tener en el campo.
Despidieron a algunos, y mi ama me proporcionó un lugar para quedarme hasta el verano,
para cuando regresaran.
En este lugar, fui herida en cuanto a mi condición espiritual.
Allí no tuve ninguna ayuda en mi viaje espiritual, sino más bien lo contrario,
por el mal ejemplo y la conducta vana e irreligiosa en aquella familia.
Por lo tanto,
les aconsejo a los jóvenes que tengan un gran cuidado con las compañías que mantienen,
y que huyan de las malas amistades como lo harían de una serpiente.
Porque verdaderamente, tales compañías resultaron como veneno para mí,
ya que ayudaron a alejar de mi mente las cosas buenas, produciendo así el olvido de Dios,
y causando tiempos de dolor cuando el Señor me lo mostraba.
Pero alabado sea Su nombre, Él no me permitió continuar en este estado por mucho tiempo;
pues mi cojera empeoró en ese entonces,
y llegó el tiempo en que tenía que dejar esta familia
y regresar a mi antiguo amo (el juez),
donde anhelaba estar, porque era una familia más ordenada.

Me hubiera gustado estar sana de mi cojera en mi propio tiempo,
para poder cumplir con todos mis deberes;
pero encontré que entre más me esforzaba por curarme, peor me ponía,
tanto así que me vi obligada a regresar a la casa de mi padre.
Esto no fue una pequeña prueba para mí, a causa de mi madrastra;
pero alabado sea el Señor,
el día de Su amor seguía siendo extendido y aunque vino con juicio,
estaba mezclado con misericordia.
Grande era el dolor en mi cuerpo, y el dolor de mi mente era mucho mayor.
En esta aflicción, como el Israel de antaño, clamé al Señor por ayuda;
porque vi claramente que si Él no me ayudaba, quedaría deshecha para siempre.
Renuncié a la ayuda del hombre, pues la había buscado en vano en muchas ocasiones,
así que mis clamores y oraciones a Dios para que me restaurara eran grandes y muchos,
con la determinación de servirle en novedad de vida.
Este era el pacto que estaba lista a hacer con Él. ¡Oh,
las incomparables misericordias y la gran paciencia
de un Dios bueno y compasivo hacia una pobre,
desconsolada, e indigna criatura!

La fidelidad y constancia de mi querido amigo Daniel
Smith (posteriormente mi esposo) fue sorprendente,
quien durante toda mi angustia y debilidad, nunca disminuyó su amor hacia mí,
sino que fue constante,
a pesar de que llegué a ser una pobre lisiada y andaba con muletas.
Él era un hombre atractivo y apuesto,
y para ese entonces había adquirido una granja en
donde era probable que le fuera muy bien,
y pudo haber encontrado a una mejor pareja que yo.
Pero él, siendo un hombre honesto, nunca tomó en cuenta mi cojera,
sino que se mantuvo fiel y constante,
y esperó dos años para ver cómo el Señor trataría conmigo.
Finalmente, viendo que mi salud no mejoraba,
él sin embargo me propuso matrimonio y así nos casamos.
En él encontré un esposo fiel, tierno y amoroso;
que me proveyó de todas las cosas necesarias y adecuadas;
un favor y una bendición que espero nunca olvidar.
Su constancia y fidelidad son dignas de ser registradas.
La bendición de Dios fue su recompensa en esta vida,
y no tengo duda de que él se encuentra en paz con su Dios y el mío.

Unos cuantos meses después, mi cojera mejoró,
de modo que dejé mis muletas y podía caminar muy bien.
Pero, ay, ¡qué lamentable! me extravié del camino;
porque habiéndome recuperado de mi cojera, y habiendo cobrado fuerzas,
al vivir satisfecha en mi corazón con un esposo amoroso,
y prosperando en las cosas externas,
olvidé (como el Israel de antaño) de los tiernos
tratos y las misericordias de un Dios tan piadoso,
como también de las promesas y pactos que había hecho con Él;
y me di la libertad de hacer todo lo que mi mente inconstante deseara.

Así continué por alrededor de un año y medio después de que me casé;
hasta que el Señor se compadeció y miró mi miserable
y desdichada condición e puso Su mano sobre mí,
para despertarme de este falso reposo,
con una enfermedad por la que estuve a punto de morir.
Entonces, estando mi conciencia completamente despierta,
contemplé con asombro mi infidelidad y desobediencia.
El horror y la condenación se apoderaron rápidamente de mí,
y el Testigo se levantó dentro de mí, causando una gran angustia de mente;
y en esta condición me veía tan solo a un paso de salir del tiempo a mi juicio eterno.
Vi que si moría en este estado, mi porción sería con los incrédulos y desobedientes,
en el lago que arde con fuego y azufre por los siglos de los siglos.
Y de hecho, hubiera sido justo que Dios me cortara en ese entonces,
por haber roto y desobedecido el pacto que hice con Él. ¡Oh,
fue terrible ver mi tiempo tan corto, y la obra que tenía que hacer tan grande!
Permanecí bajo el horror y el asombro,
preguntándome cómo soportaría el tormento que merecía. Que estos pensamientos
calen profundamente en el corazón de los que leen estas líneas,
para que se preparen y estén verdaderamente aptos para el reino de descanso y paz,
cuando la muerte los mire a la cara.
Entonces será más fácil para ellos de lo que fue para mí;
pues ningún ser mortal puede describir la ansiedad
en la que permanecí por varias noches y días,
esperando esa terrible sentencia: "`Parte ahora, porque tu tiempo aquí no será más.`" Oh,
los fervientes clamores y oraciones que elevé al Señor en ese tiempo;
para que se complaciera en perdonarme una vez más;
y le rogué a todos los que se me acercaban que oraran por mí. Mi clamor era,
"`Permíteme un poco más de tiempo,
y pruébame una vez más y me convertiré en una nueva criatura.`"

Así me aventuré, una vez más, a entrar en pacto con el Señor;
quien en gran misericordia y piedad, me miró,
me perdonó y me rescató del borde de la muerte.
¡Oh, las infinitas misericordias de Dios! ¡Cómo podré expresarlas!
Gloria eterna sea dada a Él; que todo mi ser alabe Su santo nombre.
Y al ver que a Él le plació escuchar mi petición, y levantarme de nuevo,
y darme un poco de fuerzas,
el recuerdo de mi estado anterior se apoderaba de mí cada día y exigía el cumplimiento
de mis votos y promesas de convertirme en una nueva criatura.

Desde entonces comencé, si bien recuerdo, a vivir de la siguiente manera:
No dejaba de orar tanto por la mañana como por la noche,
leía las Escrituras y otros libros que consideraba buenos,
y asistía frecuentemente a las reuniones de adoración pública cada vez
que podía. También me propuse a ser muy consciente de mis palabras y acciones,
y de actuar con rectitud delante de todos los hombres.
Y vi que debía caminar muy humildemente delante del Señor,
para convertirme así en una nueva criatura;
pues Él me permitió ver que era santidad lo que El demandaba de mis manos,
y que era mi deber perseverar en ella, no por un día, una semana, un mes, o por un año;
sino que si deseaba ser salva, debía perseverar hasta el fin.^
footnote:[Mateo 10:22, 24:13; Marcos 13:13]

A pesar de que me propuse seguir rigurosamente los ejercicios mencionados,
no había transcurrido muchos meses antes de que descubriera un cambio inusual,
y una obra en mí, como nunca antes había sentido.
Los cimientos de la tierra dentro de mí comenzaron a ser sacudidos,
y esto era algo extraño y desconcertante para mí. Ahora
que me encontraba realizando estas prácticas religiosas,
tenía la esperanza de que ahora experimentaría paz y consuelo;
¡pero me topé con todo lo contrario!
En lugar de paz vinieron problemas y penas, guerras y disturbios.
Temía que mi condición fuera tal, que nunca había habido una como esa,
sin comprender en ese entonces que "`el mensajero del pacto estaba
viniendo a Su templo,`" Aquel a quién mi alma había estado buscando;
y que debía sentarse allí, es decir, en mi corazón,
como un refinador "`con fuego purificador,`" y como un lavador "`con jabón,`"^
footnote:[Malaquías 3:1-3 RVG]
para purificar Su templo que había sido contaminado por el usurpador,
el cual había hecho su morada allí desde hacía mucho tiempo.
Oh, en verdad fue un tiempo muy largo en el que el Señor
de vida y gloria no pudo entrar en Su morada,
habiendo esperado y tocado la puerta por casi veinte años,
durante los cuales yo había acumulado bastante pasto para el fuego,
y mucho trabajo para el refinador,
cuya mano hábil y misericordiosa me preservó en el horno.
La parte mala en mí era tan grande, y la buena tan pequeña,
que pensé que todo perecería junto;
porque el calor de ese fuego dentro de mi corazón era tan grande y terrible,
que estaba lista para decir como David: "`mis huesos se descoyuntaron;`"^
footnote:[Salmos 22:14]
y en lo más profundo de mi angustia, el enemigo atacaba fuertemente con sus tentaciones.
Pero ¡oh!, la bondad de Dios hacia mí en aquel día,
porque en ese tiempo "`hallé gracia para el oportuno socorro.`"^
footnote:[Hebreos 4:16]
El antiguo adversario era fuerte, y no estaba dispuesto a perder su morada,
ni a que sus bienes fueran saqueados.
Espero nunca olvidar las luchas que sentí en aquellos tiempos;
y mi deseo es que estas pocas palabras de experiencia,
puedan (y creo que lo harán) ser de utilidad para algún pobre y angustiado
viajero que tenga que caminar por los mismos pasos.

Pensé que si me hubiera encontrado con un relato de alguien
que hubiera atravesado por las mismas pruebas,
habría sido de cierta ayuda para mí. Escudriñé las Escrituras de principio a fin,
y leí varios libros, pero pensé que ninguno podía hablar claramente a mi estado.
En ciertas ocasiones, el tercer capítulo de Lamentaciones, muchos de los Salmos,
y el séptimo capítulo de los Romanos me alcanzaban un poco,
por lo que surgía una pequeña esperanza al pensar que los
autores de estos libros habían pasado por algo similar.
Pero, ¡oh, los amargos susurros de satanás,
y los pensamientos que pasaban por mi mente eran precisamente
los que mi propia alma aborrecía! Sin embargo,
las insinuaciones del enemigo eran tales,
que me culpaba de ellos como si fueran míos. Pero el Señor, en Su propio y debido tiempo,
me permitió ver que él ha sido mentiroso desde el principio.^
footnote:[Juan 8:44]

Verdaderamente,
si la secreta mano poderosa no me hubiera sostenido
en medio de este estado de gran confusión,
seguramente habría desmayado,
y perecido en la profundidad de la desesperación. El día y la noche eran iguales para mí;
no había forma de huir de la presencia del Señor,
o de Sus justos juicios que me perseguían y que ahora eran derramados sobre la naturaleza
transgresora dentro de mí que había permanecido allí por bastante tiempo y echado raíces.
Ahora, el fuego del refinador se había puesto muy caliente,
a fin de quemar la escoria y el estaño. ¡Oh,
feliz es el hombre o la mujer que permanece en el día de Su venida;
porque estoy segura de que "`Su aventador está en
Su mano,`" y si los hombres se someten ante Su aparición,
Él hará por ellos lo que ningún otro puede, a saber: "`limpiará Su era,`"^
footnote:[Mateo 3:12]
que es el corazón del hombre, donde toda la paja debe ser quemada.

Este es el bautismo que hace bien a las personas.
Que el Señor lleve a miles más a través de esta experiencia
interna a fin de preparar una ofrenda a Dios en justicia;
porque nada menos que esto servirá, o permanecerá en el gran y notable día del Señor.

De esta manera, el Todopoderoso (en Su inmensa bondad) trató conmigo,
pues Sus juicios estaban mezclados con misericordia hacia alguien tan indigno como yo.
Y mientras continuaba con paciencia, esforzándome en proseguir hacia la meta,
pasé por varios estados internos.
Sin embargo, gracias a la ayuda de la luz de Cristo (sin la cual,
seguramente habría caído en un desierto horrible y yermo,
rodeado de muchos peligros) llegué a experimentar, bajo la dispensación del Evangelio,
eso que el Israel de antaño atravesó mientras estaba
en la tierra de Egipto y a través del mar Rojo;
pues experimenté su peregrinaje en lugares profundos,
con su subida a las orillas de la liberación,
y también sus viajes a través de un desierto grande y espantoso, de serpientes ardientes,
y de escorpiones, y de sed, donde no había agua, como lo describe Deuteronomio 8:15.

Es maravilloso pensar que pude ser preservada a través de estos diversos estados,
sin la ayuda de ningún instrumento externo, que (bendito sea Dios) muchos tienen hoy.
Porque durante ese tiempo aún estaba bajo los maestros asalariados,
a los que recurría con mucha frecuencia,
felizmente me habría establecido bajo su tutela si hubiera podido encontrar así la paz.
Era fiel en mi asistencia a la casa del campanario; pero entraba triste y triste salía,
semana tras semana, y mes tras mes,
buscando al Señor vivo entre las formas y sombras muertas, pero sin poder hallarle allí.

Y no es de extrañar que esta fuera mi experiencia,
porque carecía del verdadero conocimiento del Señor Jesucristo,
a quien mi alma deseaba más que cualquier deleite externo.
En aquel tiempo,
me afligía profundamente contemplar la esterilidad tanto del sacerdote como de las personas.
Esperaba encontrar algunos frutos de sobriedad,
especialmente durante el tiempo de adoración; pero vi que algunos eran ligeros y vanos,
con una apariencia de orgullo; otros eran rudos y descuidados;
y algunos dormían. Y había tan poca seriedad,
que a menudo estaba dispuesta a decir para mí:
"`¿No existen personas que sirvan al Señor mejores que éstas?`"
Porque observaba con dolor que ellos hablaban de
sus granjas y negocios hasta llegar a la misma puerta,
y luego, tan pronto como salían, continuaban; lo cual me parecía incorrecto.
Pero así continué bajo mi ejercicio, terriblemente abrumada y abatida en mi espíritu,
deseando por la mañana que fuera la tarde, y por la tarde deseando que fuera la mañana.
Verdaderamente el horror en que me encontraba era muy grande,
tanto que a menudo deseaba nunca haber nacido.

Sin embargo,
no pasó mucho tiempo antes de que experimentara algo de ternura brotando en mi corazón,
que había estado endurecido por tanto tiempo.
Era capaz de llorar debido a mi estado perdido y muerto;
pero aún no sabía dónde buscar o esperar la aparición de Cristo,
aunque había sentido todas estas obras y luchas internas.
Y cuando sentía un poco de alivio y consuelo, lo sentía dentro de mí;
porque ciertamente _allí_ estaban mi dolor y mi herida.
Pero no sabía entonces que Dios estaba tan cerca de mí,
ni entendía quién era el que llevaba consuelo a mi alma.
Pensaba que Dios solo moraba en los cielos de los cielos;
pues las escrituras me eran aún como un libro sellado,
y no sabía que Él pudiera estar tan cerca de mí, con Su luz,
para permitirme ver las distracciones de mi mente,
y los pensamientos e intenciones reales de mi corazón. Aún así,
en ocasiones sentía cierta calidez en mi corazón,
acompañada de un suspiro hacia Dios con estas palabras: "`¡Oh Dios,
hazme como a una de Tu rebaño, una oveja de Tu pasto!`"
Estos clamores a Dios, y nada más, daban vueltas en mi corazón por varios meses;
pues este fue el primer buen deseo que Él engendró en mí
después de llevarme a través del juicio por el pecado.
Entonces la luz, o el buen Espíritu de Cristo (que es uno),
me llevó a ver claramente que no me encontraba en comunión con Su rebaño. Por tanto,
el clamor permaneció: "`Señor, hazme como a una de Tu rebaño,
una oveja de Tu pasto;`" porque aún no sabía quiénes eran, ni dónde estaban reunidos.

Pero mientras continuaba bajo estos ejercicios,
al Señor le plació darme a conocer a Su pueblo,
después de muchas noches y días de aflicción. Pero esto
verdaderamente resultó ser una gran cruz para mí,
y pasé por grandes sufrimientos antes de que estuviera dispuesta a someterme
a ser considerada como una necia entre el pueblo de Dios,
con el que ahora tengo verdadera unidad, y bendigo a Dios por el privilegio.

Si alguien me preguntara y dijera, "`¿Cómo el Señor te mostró este pueblo?`"
Yo les daría, en mucha simplicidad e integridad de corazón, esta respuesta verdadera:
A medida que continuaba bajo el ejercicio antes mencionado,
esto frecuentemente rondaba por mi mente,
"`Ve a los Cuáqueros;`" de una manera tan clara para mi
entendimiento como si hubiera escuchado una voz audible.
Pero no me apresuré a ceder ante esta manifestación,
temiendo y dudando de que fuera el enemigo de mi alma buscando engañarme y seducirme,
y conducirme al error;
entonces continué asistiendo a la adoración pública de la iglesia de Inglaterra.
Finalmente no podía encontrar paz ni consuelo allí, y la voz todavía me seguía diciendo:
"`Ve a los Cuáqueros.`"
Sin embargo, continué demorándome por las razones antes mencionadas.
Entonces me vino a la mente ese pasaje del capítulo décimo de los Hechos de los
apóstoles con respecto a Cornelio quién hacía muchas limosnas al pueblo,
y oraba a Dios siempre,
y un ángel de Dios entró donde él estaba para dirigirlo
a que enviara a llamar a Simón Pedro,
quien le iba a decir lo que tenía que hacer.
Estas escrituras fueron abiertas en mi mente con gran claridad;
pero a pesar de esto razoné internamente,
diciendo en mi corazón:--"`En cuanto a Cornelio, yo sé que un ángel lo dirigió;
pero en cuanto a mí, ¿qué veo?
Sólo escucho, por así decirlo, una voz dentro de mí, diciendo,
'`Ve a los Cuáqueros,`' y puedo ser engañada si le presto atención.`"
Así luché en contra de los movimientos del Espíritu de la Verdad,
sin saber que me encontraba bajo la dispensación donde ahora Dios "`habla por su Hijo,`"^
footnote:[Hebreos 1:2 RVG]
en los corazones de Su pueblo.

Sin embargo, fue tal la misericordia y el amor de Dios hacia mí,
que durante este tiempo de mi ignorancia e infancia espiritual,
Él se complació en seguirme con gran misericordia;
así que puedo decir con toda certeza que experimenté
el cumplimiento de la Escritura que dice,
"`Tu pueblo se te ofrecerá voluntariamente en el día de Tu poder.`"^
footnote:[Salmos 110:3]
No era nada menos que el poder de Dios lo que me constriñó
a ir y escuchar qué clase de doctrina predicaban,
porque solo había oído predicar una vez a alguna de esas personas,
y eso había sido cinco o seis años atrás. Y tras haber luchado y razonado largamente,
pregunté dónde se reunían los Cuáqueros, y fui informada del lugar y el día. Fui,
sin decirle a nadie hacia dónde me dirigía, ni le hablé de mi condición a nadie,
pues ni podía. Cuando llegué a la reunión,
vi allí a un pequeño grupo de personas esperando en el Señor, y después de un tiempo,
un siervo de Dios se levantó y declaró cosas que nunca antes había oído decir a nadie,
palabras que describió perfectamente mi estado presente,
y pude atestiguar de su veracidad.
El poder que acompañó al testimonio alcanzó al testigo de Dios en mi corazón;
y un celo por Él fue levantado dentro de mí,
mediante las expectativas que fueron engendradas
por la predicación de la Palabra de verdad.

Cuando finalizó la reunión, me fui con alegría y con gozo de corazón,
y mi entendimiento fue (en cierta medida) abierto.
Una medida de fe surgió también en mí de que el Señor aún seguía considerándome,
al ver que mi condición había sido expuesta tan claramente
por un siervo del Señor que nunca antes había visto.
Solamente el Señor conocía mi condición durante ese tiempo;
y mientras continuaba fiel a lo que Él me manifestaba,
el Todopoderoso se complacía en desnudar su brazo para liberarme de los muchos
y varios ejercicios con que me enfrenté por causa del Evangelio.

Poco después de recibir la verdad,
me encontré con muchas clases de enemigos que el viejo adversario levantó;
pero bendito sea por siempre el Dios de mi vida,
que me dio poder y dominio sobre mis enemigos internos,
y también me libró de los externos.

Cuando se supo de mi asistencia a las reuniones,
tanto en mi familia como también en el vecindario,
el diablo levantó algunos instrumentos malvados con el fin
de volver a mi esposo en contra de mí. Mi querido esposo,
que había sido tan tierno y amoroso conmigo durante todos los días hasta entonces,
se volvió grosero, y su amor se convirtió en odio y desprecio.
Fue algo muy duro para mí sufrir esto de parte de alguien a quien amaba tanto;
pero al Señor le pareció bien permitirlo, para probarme,
para ver si yo amaba a alguien más que a Él. Algunas veces,
cuando me estaba vistiendo para ir a la reunión, mi esposo me arrebataba la ropa;
pero esto no me importaba mucho, e iba con lo que tenía; así que pronto dejó de hacerlo.
Me hizo pasar por muchas otras pruebas, que no considero adecuado mencionar.
Pero una de las pruebas más duras que me hizo atravesar, fue esta:
al ser una persona muy tranquila en cuanto a su temperamento,
me habló muy seriamente de esta manera;
"`He llegado a una resolución en mi mente sobre qué
hacer si no dejas de ir donde los Cuáqueros.
Venderé todo lo que tengo, les pagaré a todos los que les debo,
me iré y te dejaré.`" Esto golpeó lo más profundo de mí;
pero entonces lo dicho por Jesús vino a mi mente: "`El que ama a alguien más que a Mí,
no es digno de mí.`"^
footnote:[Mateo 10:37]
Aquí se me puso a prueba, si amaba más a Jesucristo o a mi esposo;
porque uno de los dos debía ocupar la preeminencia en mi corazón. En verdad,
había llegado el momento de probar plenamente mi amor a Dios,
si era capaz de dejar a padre y madre, hermanos y hermanas, sí,
y a un esposo que había amado más que a todo, por causa de Cristo y del Evangelio.
Esta es una prueba que nadie puede conocer, sino los que atraviesan la misma experiencia;
porque estas personas ocupan un lugar muy importante en el corazón,
y sin un apoyo invisible, el alma no puede soportar tales pruebas.
Pero para aquellos cuyos corazones son fieles a Dios,
siendo santificados y limpiados por el lavamiento de la regeneración,
son capacitados para negarse a sí mismos, no solo de cosas ilícitas,
sino también de las cosas lícitas más preciadas, por causa de Cristo y el Evangelio.

Mi esposo esperó a que yo respondiera,
y después de un tiempo de sopesar en mi espíritu lo que me dijo,
le hablé con una gran sobriedad: "`Bien, esposo, si así debe ser,
no puedo evitarlo;`" explicándole que no podía, en conformidad a él,
dejar lo que había encontrado en Dios a través de la fe
en Su Hijo que había venido a salvarme de mis pecados;
ni podía abstenerme de ir a adorar a Dios entre el pueblo que tan
visible y plenamente me había mostrado ser Sus seguidores,
y entre los que había sentido y experimentado Su presencia.
Alabanzas sean dadas por siempre a Su nombre,
porque cuando se levantó una esperanza en mí,
de que a través de la fe en el Hijo de Dios,
mis pecados serían perdonados por causa de Su nombre,
no podía abandonar a mi Salvador por el amor de un esposo,
aunque nada más en este mundo era tan preciado para mí.
El Señor le permitió infligirme muchas pruebas dolorosas,
que fueron para mí como la hiel y el ajenjo mientras duraron.
Pero las recibí como si vinieran de la mano del Señor en bondad,
para probar cuán constante sería mi dependencia de Él cuando
todo lo cercano y querido de este mundo me diera la espalda;
sí, padre y madre, hermanos y hermanas;
pero nada era tan cercano y querido para mí como lo era mi esposo.

Cuando verdaderamente llegué a tomar la cruz por causa de Cristo,
me enfrenté con persecuciones de varios tipos;
pero el de la lengua fue la más difícil de soportar, y tuve una gran porción de ella,
con burlas muy crueles.
Pero por siempre sean dadas las gracias a ese poder
que me sostuvo a través de los terribles abusos,
reportes falsos, menosprecios y ofensas.
El simple recuerdo de ello,
inclina mi corazón y humilla mi espíritu en el sentido
de la bondad de Dios hacia mí en ese día,
que me permitió con paciencia atravesar toda esta contención de lenguas,
hasta que le plació al Señor eliminar de mi camino a muchos de mis perseguidores y calumniadores,
algunos de los cuales tendré la oportunidad de mencionar.

Como se dio a conocer que me había convertido en una Cuáquera,
el sacerdote de la parroquia, cuyo nombre era John Berrow, habiendo escuchado de ello,
vino a visitarme.
En medio de su discurso y razonamientos,
fue tan insolente como para atreverse a decirme que los Cuáqueros negaban las Escrituras,
y la resurrección, y a Jesucristo hombre quién murió fuera de las puertas de Jerusalén;
y que solamente creían en un Cristo que estaba dentro de ellos.
Ante lo dicho, yo respondí, "`No, ellos no dicen eso; ni predican esa doctrina.`"
A lo que respondió, "`Puede ser que no lo digan aún, hasta que te hayan atrapado.
No puedes discernir su anzuelo, ni su píldora mágica.
Ellos sostienen una doctrina muy peligrosa, y se encuentran en una herejía destructora.`"
A esto, solamente respondí, "`Si ellos negaran a Cristo,
nunca sería una Cuáquera;`" y así, siguió su camino.
Y después de una gran lucha de cuerpo y mente, escudriñando las Escrituras,
y comparando sus doctrinas y principios con ellas,
descubrí que este sacerdote era un calumniador.

Algunos años después de esto,
sentí una gran carga sobre mi espíritu de ir al lugar público de adoración de ese sacerdote,
y acusarlo de esta falsedad para vindicar a los profesantes de la verdad,
y para aliviar mi propia consciencia.
Más adelante tendré la oportunidad de mencionar este evento;
pero ahora procederé a decir algo con respecto a esos instrumentos antes mencionados,
que fueron los responsables de ocasionar gran confusión a mi querido esposo,
y de ser un gran ejercicio para mí.

Una cocinera que vivía con el juez en donde yo servía, y una criada mía,
siendo ambas de un mal espíritu,
no les importaba inventar mentiras y decir malos reportes
sobre mí. Pero el Señor dio a conocer su maldad,
y mi inocencia, en Su debido tiempo.
Mi criada,
por medio de sus historias y conducta engañosa en la casa de la familia del juez,
buscó ser la preferida de ese lugar,
pues sabía bien que a la esposa del juez le gustaba escuchar historias acerca de mí,
debido a su aversión por los Cuáqueros.
Pero en menos de seis meses, después de dejar de ser mi criada,
descubrieron que era una ladrona.
Ella huyó de la parroquia y nunca más la volví a ver.
En cuanto a la cocinera, poco tiempo después se volvió muy pobre,
y a menudo yo la ayudaba.

Otras dos personas que eran muy severas conmigo, fueron la esposa del juez y mi suegra.
Las dos criadas que mencioné anteriormente,
las habían llenado de tanta amargura contra mí, que angustiaron bastante a mi esposo,
poniéndolo en mi contra.
Sobre todo la esposa del juez me hizo atravesar por grandes dificultades.
Sin embargo, esto no duró mucho tiempo,
porque unos meses después de que fui convencida de la verdad,
ella se fue a Londres donde permaneció por un tiempo.
Y cuando llegó el momento de su regreso, y un carruaje fue provisto para llevarla a casa,
la muerte la sorprendió y fue llevada a la casa muerta.

Como mi suegra estaba llena de ira y de amargura hacia mí,
traté de calmarla con súplicas, y al familiarizarla con algunos de mis ejercicios,
explicándole que no fui donde los Cuáqueros en rebeldía de mente, o por voluntad propia,
ni con ninguna mala intención de arruinar a mi esposo,
como algunos decían. Pero cuando comencé a hablarle sobre estas cosas,
se enfureció amargamente, y me reprochó terriblemente,
diciendo que yo sería la ruina de su hijo, es decir, de mi esposo.
No pude en ninguna manera calmarla, ni quiso escuchar lo que tenía que decirle,
sino que se alejó de mí con mucha ira, diciendo:
"`¡No te soportaré más!`" Se fue a su casa, en donde pronto cayó enferma y murió,
y fue sepultada en menos de una semana.

Pero el enemigo pronto agitó a otra persona, el padrastro de mi esposo.
Una vez vino a nuestra casa, lleno de prejuicio en contra de mí,
y trajo un libro grande junto con él, y luego se sentó. Mi esposo no tardó en llegar,
y ambos se ensañaron contra mí, reprochando a los Cuáqueros.
Intenté salir de la casa, pero mi esposo me lo impidió,
pues se puso contra la puerta para impedir mi salida.
En esos días, no podía hablar o defender mucho la verdad; pero bendito sea el Señor,
estaba dispuesta a sufrir por ella de muchas maneras;
pero lo que provenía de mi esposo era lo más difícil de soportar para mí,
pues lo amaba como a mi propia vida.
En ese entonces, no llevábamos más de dos años de casados,
así que si Dios no me hubiera sostenido, ciertamente me habría desmayado.

Como mi esposo no me permitió salir cuando yo pretendía,
pusieron sobre la mesa el gran libro, y me dijeron, "`Si necesitas un libro para leer,
aquí hay uno para que lo mires;`" y me insistieron en que lo leyera.
Tomé su libro, y lo leí un rato, pero pronto lo cerré y lo dejé de leer,
porque vi que había sido escrito por el adversario de la verdad.
Luego, tomé la Biblia en mi mano, y lo primero que vi fue en el pasaje de los Salmos,
donde dice: "`Mejor es confiar en Jehová que confiar en el hombre.
Mejor es confiar en Jehová que confiar en príncipes.`"^
footnote:[Salmos 118:8-9]
¡Oh, el consuelo que sentí al leer estas palabras!
Fue para mí más que un tesoro externo, pues encontré mis fuerzas renovadas,
y me fue dada paciencia para soportarlo todo, y para sufrir en silencio.

Mi suegro utilizó muchas expresiones amargas, diciendo que si él fuera mi esposo,
nunca soportaría tal cosa, insinuando que él me dejaría;
lo dijo estando mi esposo presente, quién me había amenazado con lo mismo en el pasado.
Entonces, el padrastro de mi esposo comenzó a maldecir y jurar,
por lo que no pude evitar reprenderle (usando el lenguaje simple).
Pero esto lo alzó en tal ira que parecía un loco, maldiciendo y diciendo: "`¡No me tutees!
Y de una manera muy dura, me dijo: "`¡Una Cuáquera,
fuera de aquí! Si hubieras sido cualquier otra cosa--si hubieras sido una Bautista,
y te hubieras ido a escucharlos cada día de la semana--no
hubiera sido tan malo como esto.
Pero, ¡una Cuáquera!`"
Y nuevamente: "`Si no te vuelves de tu religión, compraré una cadena,
y te encadenaré a ese árbol de arce que está en el prado;
y allí te alegrarás de cambiar tu religión a causa del hambre.`"
Podrían mencionarse más cosas, las cuales omito para ser breve.
Mi pobre esposo no dijo mucho en ese momento,
sino que sólo me mantuvo dentro de la casa para ver
y oír lo que su padrastro me podría hacer.
Pero bendito sea el Señor, estas cosas no me afectaron.
Así que,
que todos sean animados a confiar en ese antiguo
brazo de poder que nunca falla en tiempos de necesidad,
ni nunca fallará a todos los que tienen la mirada puesta en Su gloria.

No pasó mucho tiempo antes de que el Señor los hiciera caer en el sentido de su error;
pues la siguiente vez que se vieron,
mi suegro le dijo a mi esposo de que estaba muy arrepentido
por lo que había dicho y hecho conmigo,
y que nunca más lo haría de nuevo.
Y de hecho, nunca más volvió a dirigirse a mí de esa manera,
sino que después fue muy amoroso y gentil conmigo.
Con el tiempo, la impresión sobre él fue tan grande,
que se volvió gentil y respetuoso con todos los Amigos con quién conversaba.
Posteriormente, el amor de mi esposo regresó,
y continuó siendo hasta el fin de su vida un esposo amoroso y tierno,
y un padre cariñoso con nuestros hijos.
Y por la bondad del Señor hacia él, fue convencido de que yo sufría por la verdad;
y realmente creo que murió en la fe, y que descansa con su Dios; y por esto,
y por todas Sus misericordias, que todo mi ser alabe Su nombre.

Habiendo sido una testigo por experiencia de los tratos del Señor,
y habiendo atravesado diversos estados,
al Señor le plació hacerme un instrumento en Su mano
para hablar la palabra (a su tiempo) a otros,
tanto en público como en privado; y al obedecer a los movimientos del Espíritu de Dios,
encontré paz, fuerzas y ánimo para perseverar.

Sin embargo,
primero debo hacer una pequeña observación sobre
el espíritu engañador por el que John Berrow,
el sacerdote de la parroquia de Watford, era gobernado,
el cual pude observar para mi gran dolor y tristeza.
Me sentí impulsada en espíritu a ir a reprenderlo públicamente en su casa de adoración,
debido a sus falsas acusaciones--de que los Cuáqueros negaban las Escrituras,
la resurrección,
y al hombre Jesucristo que había muerto fuera de las puertas de Jerusalén,
y que solamente ellos creían en un Cristo dentro de ellos.
Como también por estar yendo de casa en casa con el fin de desanimar a personas
que tenían una buena disposición de ir a las reuniones de los Cuáqueros,
porque notó que el interés de muchas personas disminuía con respecto a él,
ya que en ese momento se estaba despertando algo bueno entre las personas de ese lugar,
y la gente estaba buscando el reino de los cielos.

Por estas razones encontré un gran celo en mi espíritu,
de que el camino del Señor y de su pueblo no fuera tergiversado,
ni el que busca honestamente fuera desviado del camino.
Como esto había estado profundamente y por mucho tiempo sobre,
a menudo clamaba al Señor para que me permitiera cumplir con fidelidad lo que
veía que Él había requerido de mí. El asunto era importante y no me apresuré,
no sea que me encontrara corriendo antes de ser enviada.
Así pues, esperé pacientemente para estar completamente satisfecha en el asunto,
no solo por un día o una semana, sino por muchos meses;
y como la carga creció cada vez más fuerte en mí, al fin me rendí a ella,
implorando al Señor que estuviera conmigo,
y que me diera una clara comisión para un servicio tan importante.
Al Señor le plació confirmarme esto de varias maneras; no obstante,
(como el pobre Gedeón de antaño) me atreví a probar
al Señor una vez más. Así que dije en mi corazón:
"`Ah, Señor mío, si te place enviar a Tu siervo, Francis Stamper, a este pueblo mañana,
entonces estaré convencida.`"

No le había dicho a nadie lo que sentía que el Señor me había encomendado a hacer;
y le plació a Él concederme mi petición. Al siguiente día, que fue el 31 del octavo mes,
1696, cuando llegó la hora de la reunión, y los Amigos estaban en camino,
Francis Stamper no se encontraba entre ellos;
pero yo tenía la fe de creer que él vendría. Mientras
que me dirigía a la reunión con algunos Amigos,
le dije que iba a regresar para esperar por Francis Stamper;
ante lo cual algunos sonrieron,
sabiendo que él acababa de regresar a su casa tras un largo viaje.
Solo había esperado un poco de tiempo antes de que llegara,
y recuerdo muy bien sus palabras: "`¡Oh,
he sido arrastrado por mi espíritu para llegar hasta
aquí! Anoche estuve hasta tarde en Londres,
pero debo ir a Southgate.`"
Tomé nota de sus palabras, pero no le dije nada de mi carga hasta después de la reunión;
al llegar a la casa de un Amigo,
le dije lo que debía hacer y le pregunté si iría conmigo.
A lo que respondió, tras haber considerado el asunto dentro de sí mismo: "`Iré contigo.`"

Por la tarde, ambos fuimos a la casa del campanario,
nos sentamos en la fila opuesta al sacerdote,
y esperamos hasta que terminara su sermón y oración. Luego,
me levanté y le dije al sacerdote, "`Vecino Berrow,
tengo que hacerte una pregunta y deseo que tanto tú como esta asamblea me escuchen.`"
Pero, no se quedó, más bien se apuró en salir, sin escuchar lo que tenía que decir.
Viéndolo salir tan apresuradamente, me volví a la gente y le dije:
"`John Berrow vino donde mí y me dijo que los Cuáqueros
me dirían que debía negar a Jesucristo hombre,
quién murió fuera de las puertas de Jerusalén y que solamente
debía creer en un Cristo que estaba dentro de mí.`" Entonces
llevé este testimonio a todos los presentes en la asamblea,
diciendo: "`Nosotros sí reconocemos las Escrituras;
y decimos y creemos que no hay otro nombre dado bajo el cielo,
en que alguno pueda ser salvo, sino el nombre de Jesucristo,
quien murió fuera de las puertas de Jerusalén y fue sepultado, y resucitó al tercer día,
y ahora está sentado a la diestra de Dios,
glorificado con la misma gloria que tuvo antes de que el mundo fuese.`"
Luego me detuve, y Francis Stamper se levantó,
e iba a decirles algo a las personas a modo de consejo; pero uno de los capellanes,
junto con algunos otros, vinieron y nos obligaron a salir.
Me subí a uno de los banquillos,
y le comuniqué a la gente que íbamos a tener una reunión esa noche,
en nuestra casa de reuniones,
a la que podrían asistir todos los que estuvieran dispuestos a hacerlo;
y bendito sea Dios, fue una reunión grande y buena,
en donde la gloriosa presencia del Altísimo estaba con nosotros.
Y este fiel siervo, Francis Stamper,
tuvo un buen servicio para el honor de Dios esa noche,
como también en muchas otras ocasiones por estos lugares,
donde hubo gran apertura entre el pueblo y muchos fueron convencidos.

El siguiente testimonio,
es una memoria viva y fresca que brota de mi corazón y que quiero dejar para la posteridad,
de este siervo fiel del Señor.

[.embedded-content-document.testimony]
--

[.letter-heading]
El Testimonio de Alice Hayes respecto a Francis Stamper

Francis Stamper fue un hombre entregado y fiel a Dios en su época;
quien anduvo de un lado a otro por la tierra por
el honor de Dios y por el bien de las almas,
levantándose temprano y acostándose tarde.
Era un hombre laborioso en la viña de Dios y en el campo de la cosecha,
pues el Señor lo había hecho un obrero hábil y laborioso,
un soldado que no temía al gran y fuerte adversario.
El poder que acompañó a este hombre de Dios, mi amigo y hermano, fue eminente.

Estimo como una misericordia del Señor haber tenido el privilegio
de conocerlo bien en el servicio de la verdad,
como también en las reuniones.
Yo, junto con miles más, he sido refrescada bajo los testimonios vivos,
que han caído como rocío sobre las tiernas plantas,
o como las gotas que nutren a las tiernas hierbas.
Oh, el recuerdo de ello afecta a menudo mi corazón,
y el Señor bendijo grandemente su labor de amor;
pues por el poder que acompañó su ministerio,
muchos fueron convertidos "`de las tinieblas a la luz,
y de la potestad de Satanás a Dios.`"^
footnote:[Hechos 26:18]

Era un hombre de un espíritu tierno, y aunque no era de una edad avanzada,
fue un padre cariñoso para varios.
Muchos pueden atestiguar lo listo y dispuesto que estaba, en todas las ocasiones,
para ir en cualquier momento a visitar a aquellos
que estaban afligidos tanto física como mentalmente,
teniendo una palabra adecuada según sus diversas condiciones.
Y a menudo, en esos tiempos, el corazón quebrantado era sanado,
y el alma enferma de pecado era alentada.

La tristeza y el dolor por su muerte fueron grandes,
pues muchos sintieron la pérdida de un instrumento como éste; pero no en desesperanza.
Mi expectativa está firme en el Dios vivo,
y tengo la fe para creer que Él levantará para Sí más testigos y obreros fieles
en el lugar de los que le ha placido quitar y llevarse de este mundo malvado,
como Lo ha hecho con este siervo,
que se ha ido en paz y ha entrado en el descanso que Dios ha preparado para los justos.

Para concluir este corto testimonio de mi querido
amigo y fiel colaborador en la obra del ministerio,
debo decir: todo proviene del Señor y Él es digno de hacer lo que le plazca.
Todo lo que Él hace es bueno, ya sea que dé o quite, bendito sea Su nombre por siempre.

[.signed-section-signature]
Alice Hayes.

--

Después de que el Señor me probó con varios tipos de ejercicios,
se complació en probarme aún más con la persecución por los diezmos,
tanto con el despojo de mis bienes como con el encarcelamiento.
Fui sacada de mi granja y alejada de mi familia, teniendo cinco hijos sin padre,
y fui encarcelada en la prisión de Alban,
donde me mantuvieron como prisionera unas trece o catorce semanas.
El sacerdote,
junto con el expropiador me quitaron muchos bienes (tanto
en maíz como en ganado) por el valor de muchas libras,
ya que, por motivos de consciencia,
no podía pagar (en esta dispensación del Evangelio) para mantener su adoración,
ni ese yugo anticristiano de los diezmos.
En mi corazón vive un testimonio,
para animar a todos lo que están convencidos de la verdad de Dios,
a ser fieles en este asunto y en todas las cosas que el
Espíritu de Jesucristo les muestre como malas.

Hago mención de mis sufrimientos, no para presumir, sino para alentar a los débiles;
porque Aquel que sostuvo mi cabeza a través de todas mis pruebas y ejercicios,
sostendrá a toda alma sincera y honesta que anhela hacer fielmente Su voluntad.
Bendigo a Dios desde lo profundo de mi corazón,
por haberme considerado digna de sufrir por causa de Su nombre;
verdaderamente puedo decir,
que nunca permitió que yo atravesara ninguna prueba donde Él no
estuviera para ayudarme con Su poder y paciencia a sobrellevarla.
Y he sido testigo de que Su palabra se cumple,
que Él ha sido un esposo para mí y un padre para mis hijos.

Es mi deseo que todos, tanto ricos como pobres,
sean fieles a Dios en todos Sus requerimientos.
Pero, oh, tal como fue en la antigüedad, así es ahora,
la infidelidad hace que la obra avance lentamente y que el viaje se haga más tedioso.
Pero, bendito sea Dios,
hay un pequeño remanente que se ha entregado por completo a seguir a su verdadero Pastor,
Jesucristo, que ha venido en el poder de Su Espíritu y se ha revelado en un remanente,
capacitándolos así para ser testigos de Dios contra
todos los predicadores asalariados y camaleónicos.^
footnote:[La palabra utilizada aquí en inglés es "`time-server,`"
que se refiere a uno que adapta o conforma sus opiniones religiosas
y su conducta a la costumbre imperante de la época,
o se conforma con las leyes de los gobernantes actuales.]
Pues el propósito de Dios es establecer a Su Hijo sobre la cima de todo monte,
sobre todas las montañas de apariencia, y sobre toda sombra religiosa.
Creo, que con la ayuda de esa gracia que viene a través de Jesucristo,
muchos serán levantados para que den testimonio del
ministerio gratuito del Cordero de Dios.
Y feliz, sí, tres veces feliz, serán todos los que le sirvan a Dios con todo su corazón,
y también con todo lo externo que posean, si Él así lo ordena.
Oh, que nadie retenga nada de lo que el Señor demande, antes bien recuerden,
"`de Jehová es la tierra y Su plenitud; y los millares de animales en los collados,`"^
footnote:[Salmo 24:1; 50:10]
y Él sabe lo que necesitamos.
Si nos permite atravesar un tiempo de despojo de los disfrutes externos,
es solo para la prueba de nuestra fe.
Oh, que ni siquiera uno de los que sean profundamente probados,
desmaye o desconfíe del Señor, porque "`los ojos del Señor están sobre los justos,
y sus oídos atentos a sus oraciones.`"^
footnote:[1 Pedro 3:12]
Y a medida que todos confíen en Su nombre, el Dios de Israel pondrá Sus ojos sobre ellos,
y se mostrará de una manera y por medios que no imaginan.
Así que encontrarán que Él es un Dios cercano,
y nuestro pronto auxilio en tiempos de necesidad.
Por lo tanto, que todos los que temen Su nombre, confíen en Él;
porque "`la vida es más que la comida, y el cuerpo que el vestido;`"^
footnote:[Lucas 12:23]
y Él les dará a todos los que confíen en Él, vida para el alma y pan para el cuerpo;
como lo ha hecho conmigo maravillosamente.

[.asterism]
'''

La mayor parte del relato anterior fue escrito hace algunos años;
y habiendo visto desde entonces mucho más de las "`maravillas de Jehová en las profundidades,`"^
footnote:[Salmos 107:24]
me es impuesta una necesidad de añadir un poco más, según el Señor me lo permita,
para animar a mi descendencia, por la cual sufro dolores de parto en el espíritu,
y por todos los bebés y corderos de Dios,
y también los enlutados de Sion que viajan con cargas pesadas.
Por el bien de ellos,
estoy dispuesta a compartir un poco más de la bondad de Dios con la hechura de Su mano,
y a llamar a otros a la fidelidad desde un sentido
profundo de la necesidad que hay de ella.
Puedo decir, en gran humildad de espíritu, que no tengo fuerzas propias, ni poder,
ni habilidad, salvo lo que a Él le plazca darme.
Y no permitan que nada se atribuya a ese monstruo, _el yo,_
que a menudo aparece tanto en los predicadores como en los escritores,
y que se muestra como "`las moscas muertas en el perfume del perfumista.`"^
footnote:[Eclesiastés 10:1]
Oro de todo corazón, que pueda lavar mis manos en inocencia,
y ser preservada limpia de esta falta; y que solo Dios, que es el Autor de todo bien,
reciba mi alabanza y la de toda criatura que tiene aliento.
Maravillosos han sido Sus beneficios y misericordias hacia mí por encima
de muchos--la mitad de los cuales no soy capaz de expresar.

Lo que he visto y sentido en este año, 1708, es indecible,
siendo un año donde he sido llevada a las profundidades
y he contemplado mucho de las maravillas del Señor,
más abundantemente de lo que soy capaz de comunicar
ni he visto aún que se requiera de mi mano.
Por lo tanto, sólo daré al Señor Su alabanza y admiraré Sus maravillosas obras,
porque verdaderamente puedo decir, "`es maravilloso a mis ojos.`"^
footnote:[Salmos 118:23; Mateo 21:42]

Al encontrarme muy débil en mi cuerpo,
el Espíritu me condujo al bajo valle de profunda humildad.
Sin duda, al entrar en una comunión más cercana con Cristo el Señor,
habrá un abatimiento muy grande en la criatura y
toda carne será llevada al silencio en Su presencia,
para que Su voz sea escuchada,
y Sus movimientos sean contemplados en Su templo con esa majestad en la que Él aparece.
Oh, ¡cuán excelente y glorioso es contemplarlo!
Ruego de Su generosa mano (con gran humildad y lágrimas),
que mi alma pueda morar siempre delante del Señor.
En esa fe viva que es coronada con victoria,
albergo la esperanza de que a medida que siga haciendo el bien hasta el final,
por causa de Su Hijo, llegaré al puerto de descanso anhelado,
donde todos los justos cantarán aleluyas para siempre.

Le agradó al Señor darme a conocer Su verdad alrededor del año 1680,
por medio de esa sierva del Señor, Elizabeth Stamper;^
footnote:[La hermana de Francis Stamper]
y sin presumir, puedo verdaderamente decir que, desde ese momento hasta ahora,
he sido muy cuidadosa en obedecer Sus santos designios
y voluntad tal como me han sido manifestados.
Y para animar a otros a la fidelidad, puedo decir que no he pasado ni un solo día,
desde que conocí al Señor, sin Su presencia--en mayor o menor medida--de modo que,
bendito sea Dios, no ha habido ni gritos de alarma en mis calles.
Porque he dicho y sigo diciendo, que, si no hubiera una recompensa futura,
aún así el consuelo presente de la obediencia es un aliento suficiente
para que los hijos de los hombres teman a Dios y guarden Sus mandamientos.
Aquellos que lo hagan, vivirán por ello; esto es, vivirán por la vida del Hijo de Dios;
porque en verdad, Él ha venido para que tengamos vida,
y es por medio de la obediencia que la abundancia de Su vida es conocida.
Y esta inmensa bondad de Dios para con la humanidad no se debe a ningún mérito nuestro,
sino debido a Su gran misericordia y amor a Su hijo.
A través de Su preciosa sangre,
todos gozamos de estos grandiosos beneficios que se incrementan tanto
para el alma como para el cuerpo en nuestra sumisión a Su yugo,
y en la medida que aprendemos de Él, quién es el modelo a seguir en cada era.

Moisés, en el monte, hizo su obra según el modelo,
a través de la sabiduría de nuestro Dios.
David, Su siervo, dio órdenes a su hijo Salomón y a los ancianos,
sobre cómo llevar a cabo y construir esa gran casa que fue gloriosa en su tiempo.
Pero ¡cuánto más gloriosa es esta dispensación de
luz y gracia que brilla desde el Hijo mismo,
la imagen expresa del Padre, en nuestros corazones;
por la que ahora podemos ver nuestro camino,
seguir el modelo y no tropezar donde muchos otros han caído!
Algunos se han estancado de manera inamovible a las formas
y a las manifestaciones externas de las cosas buenas,
que no eran más que sombras,
porque no quieren llegar a la sustancia o al modelo que da a conocer el Espíritu,
que es suficiente para enseñar todas las cosas necesarias
para la eterna salvación. Por ende,
si los hombres tropiezan aquí, debe ser porque "`aman más las tinieblas que la Luz,`"^
footnote:[Juan 3:19]
y en sus corazones prefieren permanecer espiritualmente en Egipto,
como esclavos bajo Faraón,
en lugar de acercarse al lugar donde la luz y el bien se pueden disfrutar.

Oh, ¿qué se puede decir para avivar a los hijos de los hombres,
para que se despierten y dejen de dormir en el lecho de la ignorancia?
¡Levántense e inscríbanse en la escuela de Cristo,
que es este modelo del que les he estado hablando! Él ha dado una
medida de Su propio Espíritu puro a todos para provecho,
y para que aprendan a leer internamente, y a pedir de tal modo que reciban.
Porque lo que se pida en la fe y en la medida de Su Espíritu,
ciertamente será respondido en Su propio tiempo.
Y como todos los tiempos y épocas están en Sus manos, así Él, en Su sabiduría,
conoce cuándo será mejor librar a la criatura de la tribulación,
y rendir honor a Su propio nombre, que es digno de toda alabanza;
porque Él es un Dios que lo ve todo,
y ninguna aflicción o tribulación puede esconderse de Él. Sin embargo,
Él debe ser buscado y esperado; y los que lo conocen confiarán en Él. Verdaderamente,
éstos saben que es "`un Dios de cerca,`"^
footnote:[Jeremías 23:23]
y un "`pronto auxilio en las tribulaciones,`"^
footnote:[Salmo 46:1]
como mi alma también lo ha comprobado.
Gloria a Su digno nombre por siempre.

Oh, tú, a quien lleguen estas palabras, sé diligente por el bien de tu alma,
mientras tengas salud y fuerzas en tu cuerpo.
Busca a Dios con todo tu corazón,
para que llegues al conocimiento de la verdad tal como es en Cristo Jesús,
y experimentes una íntima familiaridad con Él, esperando frecuentemente en Él. Entonces,
cuando el tiempo de debilidad se apodere de ti, y ningún medio mundano te sea útil,
sabrás que el ángel de Su presencia permanecerá a tu lado hasta la muerte.
Esto será un mayor gozo que diez mil mundos en esa hora.
Oh, ¡la fortaleza de Su amor!
Ciertamente, el amor de Dios es para los hijos de los hombres,
para que puedan valorar su tiempo mientras lo tienen y preparen
todas las cosas que pertenecen a la vida eterna.
Esto es, con el fin de cumplir el propósito de cada uno en este mundo, a saber,
glorificar a Dios, y "`ocuparnos en nuestra salvación con temor y temblor,`"^
footnote:[Filipenses 2:12]
lo cual debe hacerse, si es que se hace,
en el tiempo que se les da a los hombres en este mundo.

Por lo tanto, sean sabios, hijos de los hombres, y vengan y aprendan de Cristo.
Síganlo, porque Él ha obtenido la victoria,
y toda potestad le ha sido dada en el cielo y en la tierra.
Estén dispuestos, con la ayuda de Su gracia,
a seguir adelante a donde sea que Él los conduzca; porque verdaderamente,
Él les dará potestad para hollar escorpiones,
y para someter a todo espíritu inmundo bajo sus pies.
Y al ser obedientes, aprenderán a ser vigilantes en la luz,
mediante la cual podrán ver toda especie del mal.
Resistan el mal con la ayuda del Espíritu, y no le concedan ningún lugar.
Recuerden que son soldados bajo la bandera del Capitán invicto, Cristo Jesús,
que siempre ha estado al lado de los Suyos en todas las eras,
quienes por su fidelidad salieron de este mundo,
aunque muchos han sellado con su propia sangre sus
testimonios a favor de nuestro Dios y el Cordero,
que fue su Capitán y que los sacó de este mundo en victoria, llevando Su marca.

Oh, ¿por qué alguien no seguiría al Señor,
quien puede ayudar tanto externa como internamente a todos
los que se mantienen por Él y por el honor de Su nombre?
Porque en verdad, ¡Su nombre es una torre segura,
que ha resistido con poder todos los instrumentos que el diablo
ha levantado en cada época para afligir a los hijos de Dios!
En cada dispensación el malo ha perturbado al bueno; sí,
el león aún busca devorar al cordero, y el lobo caza su presa por la noche.
Pero, gloria a Dios, el verdadero Pastor es conocido, y Su poder aún se siente,
en el que todos los justos han confiado hasta el día de hoy.
Y los vivos ahora pueden decir,
"`Su poder es el mismo que era en el principio--una cortina sobre los justos,
y un refugio en los días de angustia,
cuando las armas de iniquidad se desatan y los codiciosos hacen el mal.`"

A los que juran, mienten, cometen adulterio,
o llevan una vida envuelta de cualquier otra maldad,
permítanme que los exhorte a arrepentirse y a apartarse de la impiedad de sus caminos,
y de los pecados que tan fácilmente los envuelven.
No sigan siendo esclavos del diablo;
porque él es un mal amo y la paga que da es la misma que recibirá por sus propias acciones.
Por lo tanto, todos los que están distanciados de Dios por causa de la maldad,
aléjense de ella mediante un verdadero y oportuno arrepentimiento,
para que conozcan lo que significa ser lavados con las aguas de regeneración,^
footnote:[Tito 3:5]
y limpiados del pecado a través de la sangre del Cordero.
Así experimentarán las renovaciones de Su favor,
que serán como el bálsamo de Galaad que sanará completamente su herida,
y los hará fuertes y aptos para el servicio de Cristo nuestro Señor.
Él es el mejor Maestro al que un hombre o una mujer pueda servir,
y Él da la vida eterna.
Pero todo el que se acerca a Él debe "`creer que es galardonador de los que le buscan,`"^
footnote:[Hebreos 11:6]
y que no puede servir a dos señores.
Deben renunciar al diablo, su antiguo señor, y a todas sus obras,
junto con la pompa y las vanidades de este mundo.
Y como buenos soldados, deben seguir al Capitán de su salvación con toda perseverancia,
por mala fama y por buena fama,
manteniéndose junto a la bandera--el Espíritu de la Verdad.
Si hacen esto, entonces pueden orar al Dador por lo que necesiten;
ya sea pan para sus almas o para el cuerpo, o por fe, esperanza, coraje,
por la armadura de luz, o por cualquier otra cosa que necesiten.
Sean valientes y pidan,
y recibirán el doble de consuelo por todas las dificultades
que sufran por Cristo y por el Evangelio.
Y a cambio de la vida que han perdido (que llevaban en la vanidad y en la maldad),
encontrarán una vida que la supera cien veces más
en paz y gozo interno a través del Espíritu Santo.
Sométanse a la voluntad de Dios, que los ha llamado con un supremo llamamiento,
para que puedan escuchar a Su Hijo y lo obedezcan en todo hasta el final.
Por tanto, sean buenos soldados, como ese bendito apóstol que "`peleó la buena batalla,
y guardó la fe.`"^
footnote:[2 Timoteo 4:7]
Oh, soldados fieles, sigan adelante, y no teman ni se desanimen,
porque un ¡ay! viene sobre los tales;
pero sean valientes y celosos por la verdad en la tierra,
según el conocimiento que Dios les dará. Que sean hallados incrementando sus talentos,
sea que se les haya dado cinco, dos, o uno; por más pequeño que sea.
Porque si sus corazones están sazonados con la gracia de Dios,
su deleite estará en Su tesoro,
y serán testigos de un incremento en eso que los beneficiará al final de su batalla,
ya sea larga o corta.

Si caminan en fidelidad, todo terminará bien.
El cuidado de Dios sobre Sus hijos y Su pueblo es el mismo en todas las eras.
Soy testigo de ello, aunque sea un pobre gusano y una sierva inútil;
pues si he obedecido Su mandato, fue porque era y todavía es mi deber razonable.
Las Escrituras son veraces cuando dicen; "`Los ojos de Jehová están sobre los justos,
y atentos sus oídos al clamor de ellos;`"^
footnote:[Salmos 34:15]
porque Él es el Dios y el Padre de las misericordias,
y se deleita en reunirse con los Suyos para hacerles el bien.
Él no se complace en afligir a los hijos de los hombres
más que para someterlos a Su Hijo,
a fin de que lleguen a conocer el estado de adopción,
y aprendan a someterse a Su voluntad celestial.
Su voluntad es que todos los hombres en todas partes se arrepientan,
y lleguen al conocimiento de la verdad,
y sean salvados con una salvación eterna--salvados tanto del pecado mismo,
como de la ira que es consecuencia de él. Esta es la verdadera libertad,
ser liberado por el Señor todopoderoso, quien dijo a los Judíos,
"`si el Hijo os libertare, seréis verdaderamente libres.`"^
footnote:[Juan 8:36]

Oh, ¡que los hombres se esforzaran por esta libertad,
y creyeran en la suficiencia de esa gracia que ha llegado a través de Jesucristo,
y que aparece en el corazón para convencer de pecado en sus primeros brotes!
Mediante la fuerza de esta gracia, el pecado puede ser aplastado como un huevo de víbora,
y ser expulsado a través de la ayuda del Espíritu, que es uno con la gracia de Dios.
El objetivo de la gracia y de la venida de Jesús es, en efecto,
salvar a las personas _de_ sus pecados; y a todos los que estén dispuestos a ser Suyos,
y a creer que Él tiene todo el poder que le ha sido
encomendado en los cielos y en la tierra,
y que tiene la victoria sobre el mundo, la carne, y el diablo--a éstos les digo,
Él puede darles poder y lo hace.
Más fuerte es el que está en nosotros (esto es,
Cristo por medio de Su Espíritu) que el que está en el mundo;^
footnote:[1 Juan 4:4]
y Jesús es más poderoso para salvar, que el diablo para obligar a los hombres a pecar;
porque él solamente puede tentar.
Ceder a su tentación trajo miseria sobre nuestros antepasados;
y ceder sigue siendo aún la causa de la miseria.

El segundo Adán, el Señor de los cielos, el Restaurador de la humanidad,
no dijo que no seríamos tentados,
ni que seríamos libres de los ataques del enemigo en la tierra;
porque aquí el usurpador "`anda alrededor,`"^
footnote:[Job 1:7; 1 Pedro 5:8]
y tiene su alimento--la tierra y el polvo de ella.
Ese que fue tan atrevido como para acercarse y tentar al Señor de la gloria,
sin duda alguna atacará a Sus seguidores.
Y el Señor, sabiendo muy bien con lo que nos encontraríamos aquí,
advirtió y aconsejó a todos a "`velar y orar, para que no entren en tentación.`"^
footnote:[Mateo 26:41]
Es como si Él hubiera dicho, "`Si algún mal los angustia, no lo toquen;
sino que oren a Mí y yo los ayudaré;`" así que es el Señor quien
obra esta liberación. Dios debe llevarse toda la alabanza,
quien es el único digno; porque Sus propias obras lo alaban,
siendo maravillosamente manifestadas en esta era del mundo,
tras una larga y oscura noche de apostasía. Bendito sea Dios,
que es el Espíritu de la luz y de la pureza,
y que ahora ha irrumpido por medio de Su Hijo para alumbrar a los hijos de los hombres
en el corazón. Su Espíritu y gran poder son más fuertes que el poder de las tinieblas,
derribando y despojando las obras del viejo adversario, sí, y atando y echándolo fuera.
Y Él está preparando Su creación para un edificio celestial, para que sea una piedra,
o un pilar en la postrera casa que Dios está construyendo con piedras vivas--piedras
ciertamente rechazadas por los sabios del mundo en estos días,
pero aprobadas por Dios, que es la Piedra Angular y el Señor de todo.

Leemos que algunos en la antigüedad decían,
"`¿Qué debemos hacer para poner en práctica las obras de Dios?`"^
footnote:[Juan 6:28]
Y la respuesta (por Uno que la sabía bien) fue: "`Esta es la obra de Dios:
que crean en el que Él ha enviado.`"^
footnote:[Juan 6:29]
Oh, ¡es doloroso pensar que los hombres y las mujeres sean tan tardos de corazón
para creer en la aparición espiritual interna del Hijo de Dios!
Pero alabado sea Dios, un remanente ha creído,
y por lo tanto estos pueden clamar "`Abba Padre,`" porque Él ha hecho en ellos,
y por ellos, lo que ningún otro podría hacer,
a través de la operación del poder de Su fuerza.
Por medio de esto, sabemos que el Hijo de Dios ha venido,
y nos ha dado entendimiento para conocer al que es verdadero, "`que es Cristo en ustedes,
la esperanza de gloria.`"^
footnote:[Colosenses 1:27]
Esto es como un ancla, segura y firme,
que nunca ha fallado cuando el viento ha soplado o la lluvia
ha descendido y las corrientes de aflicción han subido.
No, no, nunca ha fallado, porque el cimiento es probado,
es una roca inamovible en cada era.
Todos los que han edificado sobre este fundamento, y han continuado en él,
se han mantenido firmes y seguros;
en cambio los que han edificado sobre la arena han sufrido
grandes pérdidas cuando su tiempo ha llegado a su fin,
y sus cimientos han sido probados.
¡Oh,
será algo terrible pasar del tiempo a la eternidad
bajo la ira de un Dios paciente y justo,
que ha sido largamente provocado!
Porque Él seguirá siendo justo en todos Sus caminos, y dará a las vírgenes insensatas,
a los hombres insensatos que edificaron en la arena, y al siervo negligente,
una recompensa de acuerdo con sus obras, conforme a lo dicho en las Escrituras;
"`Os digo que no sé de dónde sois; apartaos de mí todos vosotros, hacedores de maldad.`"^
footnote:[Lucas 13:27]

Mi corazón se deshace dentro de mí cuando pienso en el horrible
estado de ser lanzado fuera de la presencia de un Dios glorioso
que contiende largamente con los hombres por medio de Su buen Espíritu.
Pero ¡cuán lamentable es, que muchos hayan rechazado las ofertas de Su amor,
y hayan escogido sus propios caminos, negándose a ser reformados!
Por lo tanto, grande será la condenación de esos,
y espantoso será el gusano que los carcomerá cuando consideren que su tiempo se ha acabado,
y que todas las ofertas de la gracia se han ido.
Entonces, éstos verán cómo han despreciado el favor de un Dios bueno,
al escoger sus propios caminos y al hacer sus propias obras.
Oh, ¡el tiempo perdido!
Oh, ¡la pérdida del campo, y del tesoro también! Por eso,
es mucho mejor ocuparse de la obra de Dios, para que, por medio de la fe en el Hijo,
puedan experimentar cómo Él "`obra en nosotros todas nuestras obras,
por su buena voluntad.`"^
footnote:[Isaías 26:12; Filipenses 2:12-13; Hebreos 13:21]
No hay nada de lo que el hombre pueda jactarse o gloriarse.
Solamente le corresponde ser tan maleable como la arcilla en la mano del alfarero,
hasta que sea hecho una vasija para Su alabanza.
"`Porque Dios no quiere la muerte del que muere,
sino que los hombres obedezcan Sus mandamientos y vivan.`"^
footnote:[Ezequiel 18:32]
De lo contrario, no pondría delante de ellos la vida y la muerte, el bien y el mal,
y diría: "`escoge, pues, la vida.`"^
footnote:[Deuteronomio 30:19]
Esto parece dejar muy claro, que hay una elección para la humanidad,
y una oferta de salvación mientras se encuentran en este mundo;
de modo que los hombres y las mujeres pueden escoger la vida al creer en Cristo,
o la pueden rechazar a causa de la incredulidad,
la cual los aparta de Dios y del Señor Jesús, y los lleva a la muerte y a la oscuridad.

Pero bendito sea Dios, que ha llevado a un remanente al conocimiento de Su luz,
y a la obediencia a la misma.
Estos son testigos vivos de la suficiencia de Su gracia, como el apóstol de antaño que,
en grandes pruebas y tentaciones, encontró que la gracia era eficaz;
aunque encontramos que una vez estuvo en un estado donde clamó diciendo:
"`¡Miserable de mí! ¿quién me librará de este cuerpo de muerte?`"^
footnote:[Romanos 7:24]
Y también, "`Soy carnal, vendido al pecado.`"^
footnote:[Romanos 7:14]
Este fue un estado, que por un tiempo fue muy lamentable para Pablo,
cuando la tristeza se apoderó de su corazón,
y clamó a Dios quien era el que podía ayudarlo.
Y en el debido tiempo,
llegó a experimentar la suficiencia de Su gracia para sacarlo de ese estado,
y para conocer una mejor condición, de modo que pudo decir: "`Ahora, pues,
ninguna condenación hay para los que están en Cristo Jesús,
los que no andan conforme a la carne, sino conforme al Espíritu.
Porque la ley del Espíritu de vida en Cristo Jesús
me ha librado de la ley del pecado y de la muerte.`"^
footnote:[Romanos 8:1-2]
Oh, la bendita libertad que vino a los creyentes en aquel
día por medio de Cristo Jesús. Y bendito sea Dios,
Él es el mismo en este día, como lo fue entonces.
Porque esta gracia, que ha venido por medio de Cristo Jesús,
no sólo ilumina a los hombres y a las mujeres para que puedan ver su condición pecaminosa,
sino que también da poder al alma para salir del cautiverio.
Y mientras haya fidelidad en la criatura,
la suficiencia de la gracia se sigue experimentando
como la que lleva de un grado de fuerza a otro.

Por lo tanto, todos tienen razones para agradecerle a Dios como lo hizo el apóstol,
y para decir: en Él "`no hay mudanza, ni sombra de variación.`"^
footnote:[Santiago 1:17]
Porque ciertamente,
Él es el mismo de siempre para todos los que creen y siguen a Cristo
Jesús. Y todo seguidor fiel de Jesús está capacitado para decir
(y no de manera jactanciosa) que la revelación no ha cesado,
ni el Evangelio está oculto,
excepto para aquellos que se pierden a causa de la incredulidad, y que no se vuelven,
ni creen en la luz de Cristo y en su suficiencia--éstos serán sepultados en dolor.^
footnote:[Isaías 50:11]
Y a todos los que afirman que no hay un estado de redención
del pecado que pueda experimentarse de este lado de la tumba,
diciendo que están "`llenos de podridas llagas,`" y "`que no hay integridad en ellos,`"^
footnote:[Citas tomadas de la liturgia de la Iglesia de Inglaterra]
yo les digo, ¡estas quejas son ciertamente lamentables!
Sin embargo, ¿cómo podría ser de otra manera,
mientras siguen abogando por el reino del diablo, que es pecado,
oscuridad y confusión? Oh, por lo tanto,
permítanme persuadirlos para que sean reconciliados con Dios, creyendo en Su Hijo,
a quien Él ha constituido como Heredero de todas las cosas,
el cual es un verdadero Abogado,
por y en quién pueden encontrar aceptación. Y bendito sea el Señor,
hay un remanente de testigos vivos que han creído en el poder de Su aparición interna,
en el que se obtiene la victoria sobre el mundo, la carne, y el diablo.
Oh, felices son las almas que pueden creer así en Su nombre,
porque éstas serán bautizadas con el bautismo mismo de Cristo--el
bautismo del Espíritu Santo y fuego--es decir,
Su Espíritu y Palabra entrando en sus corazones como un fuego en contra de toda
especie de mal para quemarla y destruirla en su primera aparición.

Oh, que los hijos de los hombres sean sabios y teman a Dios,
y clamen a Su nombre mientras la puerta de misericordia esté abierta,
para que sus almas puedan vivir.
Ruego de todo corazón por esto, porque he gustado la bondad de la Palabra de Dios,
y he conocido algo del poder del siglo venidero.
Y habiendo gustado tanto de Su misericordia como de Su juicio,
no puedo hacer nada más que invitar y animar a todos,
a ser fieles al Señor y a todos Sus requerimientos, para que,
al final de todas las cosas, Dios tenga la alabanza (quien es digno por siempre),
y nuestras pobres almas encuentren un gozo y un consuelo
que nadie más puede dar o quitar.

[.asterism]
'''

Algún tiempo después de haber sido convencida de la Verdad, en el año 1680,
Alice Hayes fue llamada a la obra del ministerio,
y se vio impulsada a visitar las iglesias en las diferentes partes de Inglaterra.
Además, viajó por Holanda hasta Alemania, pasando por Frederickstadt,
y allí tuvo un excelente servicio para el Señor. Muchos
fueron alcanzados y convencidos por su ministerio,
siendo en la demostración y poder del Espíritu.
Alrededor del año 1712, se mudó de Hertfordshire para establecerse en Tottenham,
y los Amigos sintieron una verdadera unidad con ella,
tanto por su vida y conducta inocente y ejemplar,
como también por su don en el ministerio,
en el que fue muy útil para animar a los Amigos a
la fidelidad en cada aspecto de su testimonio.

Estando en la Reunión Anual en Londres, en el año 1720, cayó enferma;
pero como su amor hacia los Amigos de allí era fuerte, se quedó unos días más,
y luego regresó a su casa en Tottenham,
donde se debilitó cada vez más hasta que partió silenciosamente
de esta vida como un cordero.
Durante el tiempo de su enfermedad,
dio muchos buenos consejos y advertencias a su familia,
y también a los que llegaban a visitarla,
dejando caer de sus labios dulces comentarios respecto al gozo
consolador de la presencia del Señor que ella disfrutaba;
algunos de los cuales se exponen a continuación.

En una ocasión, un Amigo de Tottenham vino a visitarla, y mientras otros se acercaron,
ella dijo: "`Oh, ámense los unos a los otros,
y que el Señor los convierta en un pueblo vivo para Sí mismo,
y los preserve en perfecto amor y unidad.
Me encuentro,`" dijo ella, "`en perfecto amor hacia todas las personas.`"
Entonces, deseó que los Amigos la "`entregaran libremente a Dios;`" diciendo:
"`estoy dispuesta a morir, y espero que sea en un corto tiempo.
Pero, oh,
deseo irme exactamente en el tiempo del Señor. Y todo lo
que anhelo es que la presencia del Señor continue conmigo,
y entonces no temeré la hora de la muerte.
Mi Dios es mi resurrección y mi gloria.
Él es mi fortaleza y mi refugio, y estoy completamente resignada a Su voluntad;
y en un corto tiempo,
mi alma cantará alabanzas al Señor en el monte de Sion con todos los redimidos,
lejos de toda angustia.`"

Algunos Amigos, habiendo llegado a visitarla en otra ocasión,
ella irrumpió en un tierno estado de espíritu diciendo: "`Ahora espero en mi Dios;
y Él es un Dios de eterna bondad, y ha sido bueno para con mi alma por toda mi vida.`"
Luego dijo, "`Amigos,
no posterguen el hacer las paces con Él hasta que lleguen al lecho de su muerte.
Ya hay suficientes cosas que hacer durante estas aflicciones del cuerpo; no quisiera,
ni por el mundo entero, estar ahora sin el favor de Dios.
Que el Señor, el Dios de Abraham, de Isaac y de Jacob, mi Dios y su Dios,
los bendiga y sea un Dios para ustedes en todas sus pruebas, porque lo ha sido para mí,
y un pronto auxilio en las tribulaciones.`"

Estando varias personas jóvenes junto a ella en otra ocasión,
tiernamente los aconsejó de la siguiente forma: "`Sean buenos, y sirvan a Dios fielmente,
y no retrasen la gran obra de su día para el final;
sino prepárense oportunamente para la hora de su muerte,
para que puedan tener aceite en sus lámparas,
y estén listos para cuando llegue el momento.
Asistir a las reuniones ha sido un gran gozo para mi alma,
y encontrarme con el Señor allí. Pero, oh,
un mayor gozo para mi corazón será encontrarme con Él en el cielo,
y tener un lugar en Su reino.
Por Su misericordia, no me encuentro bajo el terror de la muerte,
sino en la verdadera paz.
Bendito sea mi Dios por siempre, Su bondad es excesivamente grande.
Quisiera alabarlo por Su bondad, pero estoy muy débil; y deseo, si es Su voluntad,
no ver la luz de otro día, pues mi aflicción es grande; pero que todo sea en Su tiempo.`"
Luego, irrumpió en oración, implorando que se facilitara su partida,
y deseando que Él la sostuviera en su aflicción, que en ocasiones era muy aguda.
Sin embargo, soportó todo con gran paciencia, con la mirada puesta en el Señor,
su consolador, bajo las más profundas pruebas y diciendo a menudo: "`Oh, Señor Jesús,
recibe mi espíritu, porque anhelo estar contigo, mi Salvador;
pero no me permitas que te ofenda, sino que espere pacientemente Tu tiempo.`"

Unos pocos días antes de que falleciera, algunos Amigos de Tottenham,
se sentaron a esperar en el Señor Dios con ella.
Su amor fue manifestado grandemente y brotaba como una fuente fresca;
y después de que un Amigo fue movido en súplica, ella irrumpió diciendo: "`Oh,
¡el amor! ¡Este es un amor que puede sentirse!
Mi Dios, Tu bondad es maravillosa,
y mi alma te alaba por el desbordamiento de Tu amor en este
momento;`" junto con muchas más expresiones dulces y celestiales.
Ella agradeció con ternura la bondad de sus amigos al visitarla,
y se despidió de ellos con lágrimas, deseándoles: que "`el Señor esté con ustedes,
y los fortalezca para que sean valientes por Su verdad,
y para que mantengan sus reuniones en Su nombre y Su poder;`" añadiendo: "`oh,
¡cuántos momentos reconfortantes hemos tenido a menudo en nuestras reuniones entre semana!
¡Cómo han rebosado nuestras copas con el amor de nuestro Padre celestial!`"
Después de esto, exhortó a todos a "`permanecer en la unidad del Espíritu de Cristo,
que cada miembro se mantenga en su lugar,
esforzándose por el honor de la verdad al mantener el buen orden en la iglesia.`"

En otra ocasión, cerca de su final, solicitó a los que la rodeaban,
que cuando la vieran dando sus últimos suspiros,
estuvieran muy quietos y recogidos con el Señor en sus espíritus,
orando que tuviera una partida fácil.
Luego, añadió: "`Todo estará bien.
Voy camino a casa.
Voy camino a casa.
He terminado con el mundo,
y todo lo que está en él. Pero oren que el Señor
derrame Su Espíritu sobre una generación joven,
para que puedan servirle en pureza de corazón.`" Más adelante dijo,
"`He peleado la buena batalla, y obtendré la corona inmortal;`" añadiendo,
"`Mi amado es mío, y yo Suya.
Él es mi todo en todo.
En Tus brazos, Señor Cristo Jesús, encomiendo mi alma y mi espíritu.`"
Las últimas palabras que se le escucharon decir (al ser su voz muy suave) fueron:
"`El Señor mi Dios me ayudará.`"

Partió de este mundo el octavo día, del sétimo mes de 1720,
alrededor de los sesenta y tres años, y fue sepultada el treceavo día del mismo mes,
en el cementerio de los Amigos en Winchmorehill.
